#!/usr/bin/env bash
set -euo pipefail

DATA_DIR=/data
mkdir -p "$DATA_DIR"

cat > "$DATA_DIR/neurai.conf" <<'EOF'
# Neurai MAINNET — generated by Docker entrypoint, do not edit by hand
testnet=0

# RPC — bound on 0.0.0.0 so other containers in the docker network can
# reach it. No host port is mapped in docker-compose, so this is only
# accessible from inside the compose network.
rpcuser=neurai
rpcpassword=changeme
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=19101
rpcservertimeout=240
rpcworkqueue=64
rpcthreads=8
server=1

# Network — no inbound P2P, REST enabled
listen=0
rest=1

# Indexes — full
txindex=1
assetindex=1
addressindex=1
timestampindex=1
spentindex=1
pubkeyindex=1

# ZMQ — only reachable from the docker network (no host port mapped)
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28332
zmqpubhashblock=tcp://0.0.0.0:28332
zmqpubhashtx=tcp://0.0.0.0:28332

disablewallet=1
shrinkdebugfile=1
daemon=0
EOF

echo "[entrypoint] neurai mainnet conf written to $DATA_DIR/neurai.conf"
exec neuraid -datadir="$DATA_DIR" "$@"
