/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/majorTomToGroundControl": {
    post: {
      responses: {
        /** Created */
        201: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            addresses?: string[];
            txids?: string[];
            token: string;
            os: string;
            chain: components["schemas"]["NeuraiChain"];
          } & { [key: string]: unknown };
        };
      };
    };
  };
  "/unsubscribe": {
    post: {
      responses: {
        /** Created */
        201: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            addresses?: string[];
            txids?: string[];
            token: string;
            os: string;
            chain: components["schemas"]["NeuraiChain"];
          } & { [key: string]: unknown };
        };
      };
    };
  };
  "/ping": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["ServerInfo"];
          };
        };
      };
    };
  };
  "/getTokenConfiguration": {
    post: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["TokenConfiguration"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            token?: string;
            os?: string;
          } & { [key: string]: unknown };
        };
      };
    };
  };
  "/setTokenConfiguration": {
    post: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              instance_id?: components["schemas"]["InstanceId"];
            } & { [key: string]: unknown };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TokenConfiguration"] &
            ({
              token: string;
              os: string;
            } & { [key: string]: unknown }) & { [key: string]: unknown };
        };
      };
    };
  };
  "/enqueue": {
    post: {
      responses: {
        /** OK */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": (
            | components["schemas"]["PushNotificationOnchainAddressGotPaid"]
            | components["schemas"]["PushNotificationOnchainAddressGotUnconfirmedTransaction"]
            | components["schemas"]["PushNotificationTxidGotConfirmed"]
          ) & { [key: string]: unknown };
        };
      };
    };
  };
};

export type components = {
  schemas: {
    ServerInfo: {
      name?: string;
      description?: string;
      version?: string;
      uptime?: number;
      last_processed_block_mainnet?: number;
      last_processed_block_testnet?: number;
      send_queue_size?: number;
      sent_24h?: number;
      instance_id?: components["schemas"]["InstanceId"];
    } & { [key: string]: unknown };
    /** @description Random id of this server's database. It changes when the database is wiped, and with it every subscription: a wallet that sees a new value must send its addresses again via /majorTomToGroundControl. */
    InstanceId: string;
    /**
     * @description Neurai chain identifier. One GroundControl instance can watch both mainnet and testnet in parallel; subscriptions are scoped by this field.
     * @enum {string}
     */
    NeuraiChain: "mainnet" | "testnet";
    /** @enum {string} */
    NotificationLevel: "transactions" | "news" | "price" | "tips";
    TokenConfiguration: {
      level_all?: boolean;
      level_transactions?: boolean;
      level_news?: boolean;
      level_price?: boolean;
      level_tips?: boolean;
      lang?: string;
      app_version?: string;
    } & { [key: string]: unknown };
    AssetAmount: {
      /** @description asset name, e.g. `MYASSET` or its owner token `MYASSET!` */
      name: string;
      /** @description amount in the asset's smallest unit (1 unit = 100,000,000) */
      amount: number;
    } & { [key: string]: unknown };
    /** @description payload for push notification delivered to phone */
    PushNotificationBase: {
      /**
       * @description type:
       *  * `2` - New transaction to one of your addresses
       *  * `3` - New unconfirmed transaction to one of your addresses
       *  * `4` - Transaction confirmed
       *  * `5` - Arbitrary text message
       *
       * @enum {integer}
       */
      type: 2 | 3 | 4 | 5;
      token: string;
      /** @enum {string} */
      os: "android" | "ios";
      badge?: number;
      level: components["schemas"]["NotificationLevel"];
    } & { [key: string]: unknown };
    PushNotificationOnchainAddressGotPaid: components["schemas"]["PushNotificationBase"] &
      ({
        /** @enum {integer} */
        type?: 2;
        /** @enum {string} */
        level?: "transactions";
        /** @description XNA the transaction sent to this device's addresses, summed over all its outputs, in the smallest XNA unit (1 XNA = 100,000,000 sat). One push covers the whole transaction. */
        sat: number;
        /** @description user's Neurai on-chain address that has an incoming transaction (the first one, if the transaction paid several of the device's addresses) */
        address: string;
        /** @description txid of the transaction where this address is one of the outputs */
        txid: string;
        /** @description Neurai assets (issue, reissue or transfer outputs) the transaction sent to this device's addresses, summed per asset; absent if none. Over FCM it arrives JSON-encoded, since FCM data values are strings. */
        assets?: components["schemas"]["AssetAmount"][];
      } & { [key: string]: unknown }) & { [key: string]: unknown };
    PushNotificationOnchainAddressGotUnconfirmedTransaction: components["schemas"]["PushNotificationBase"] &
      ({
        /** @enum {integer} */
        type?: 3;
        /** @enum {string} */
        level?: "transactions";
        /** @description XNA the transaction sent to this device's addresses, summed over all its outputs, in the smallest XNA unit (1 XNA = 100,000,000 sat). One push covers the whole transaction. */
        sat: number;
        /** @description user's Neurai on-chain address that has an incoming transaction (the first one, if the transaction paid several of the device's addresses) */
        address: string;
        /** @description txid of the transaction where this address is one of the outputs */
        txid: string;
        /** @description Neurai assets (issue, reissue or transfer outputs) the transaction sent to this device's addresses, summed per asset; absent if none. Over FCM it arrives JSON-encoded, since FCM data values are strings. */
        assets?: components["schemas"]["AssetAmount"][];
      } & { [key: string]: unknown }) & { [key: string]: unknown };
    PushNotificationTxidGotConfirmed: components["schemas"]["PushNotificationBase"] &
      ({
        /** @enum {integer} */
        type?: 4;
        /** @enum {string} */
        level?: "transactions";
        /** @description txid of the transaction that got confirmed */
        txid: string;
      } & { [key: string]: unknown }) & { [key: string]: unknown };
    PushNotificationMessage: components["schemas"]["PushNotificationBase"] &
      ({
        /** @enum {integer} */
        type?: 5;
        /** @description custom text displayed on the push notification bubble */
        text: string;
      } & { [key: string]: unknown }) & { [key: string]: unknown };
  };
};

export type operations = {};

export type external = {};
